name: depixel_app
description: DePixel Flutter app
publish_to: "none"
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  fl_chart: ^0.69.0

  # UI
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.2.4

  flutter_blue_plus: ^1.30.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
